sudo: false
cache:
  directories:
  - "$HOME/.gradle"
language: groovy
jdk:
- openjdk7
before_install:
- cat /etc/hosts
- sudo hostname "$(hostname | cut -c1-63)"
- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo
  tee /etc/hosts
- cat /etc/hosts
before_script:
- rm -rf target
script: JAVA_HOME=$(jdk_switcher home openjdk7) "./travis-build.sh"
env:
  global:
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"
  - GIT_NAME="Puneet Behl"
  - GIT_EMAIL="behl4485@gmail.com"